[package]
name = "noob"
version = "0.1.0"
authors = ["Colin Reeder <vpzomtrrfrt@gmail.com>"]

[dependencies]
futures = "0.1.18"
hyper = "0.11.22"
websocket = "0.20.2"
quick-error = "1.2.1"
tokio-core = "0.1.12"
hyper-tls = "0.1.2"
native-tls = "0.1.5"
serde_json = "1.0.10"
serde_derive = "1.0.28"
serde = "1.0.28"
tokio-timer = "0.1.2"
